### ISSUE TITLE
Question on Setting Up supply_priority

### ISSUE THREAD

**Issue by aesculus** [BuongiornoTexas/pwdusage#4]
First off this looks like an interesting ad-on to the Powerwall Dashboard and quite robust.

I am in the US so there may be some nuances between operations here and AU. I pretty much understand most of the settings in the usage.json but I have some questions as it pertains to my environment.  First some background:

Generally I rarely (only in emergencies) ever charge the PWs from the grid. They only get charged from solar. This is mostly due to agreements with US utilities and our taxation for solar based systems. It can happen a few times a year but is unpredictable. On the TOU basis we only get credit for exporting solar energy we generate. In theory we are not supposed to export energy captured from the grid and then sent back at a more profitable time (arbitrage). They will not credit us if we send more power back than we got from solar. And technically we should only be exporting during solar production periods but there is some leeway there in special cases.

The way my PWs work is that Tesla usually prioritizes filling up their state of charge during non peak periods with solar. Then use that solar energy later during peak to avoid high energy costs. I run in Cost Based mode where Tesla has algorithms to try to minimize my total costs by adjusting when and how the PWs are charged and discharged and when to send solar energy back to the utility.

We also have a small penalty (NBCs at $.03/kWh) that is added to energy sent back to the grid. That is easy to add into the cost tables.

So with this in mind I am struggling with what to do with the supply_priority settings. It would seem for my situation that this is out of my control and is solely based on what Tesla does behind the scene.

Do you have some guideance on what my settings in this area should be?

The same concerns would be on the Report section. Some of those reports may not makes sense in my situation but I may need to experiment a bit and also further understand the terms for my utility.

**Comment by BuongiornoTexas** [comment]
> In theory we are not supposed to export energy captured from the grid and then sent back at a more profitable time (arbitrage).

I can't help but chuckle that in the free-est of all free markets, you aren't allowed to free market. (Arbitrage is allowed here, but it's hard to work effectively with a home battery). But on to the actual question. 

> It would seem for my situation that this is out of my control and is solely based on what Tesla does behind the scene.

First up, supply priority is an accounting construct in pwdusage - it doesn't interact with or understand the powerwall or your utility plan usage rules. It's a convenience function for deciding how the home load energy demand (kWh) in a historical time period was met from the various sources of supply in that period (nothing to do with how the Tesla box actually manages your power). Unfortunately, we need it because the powerwall doesn't tell us how it manages this internally, so we take a guess and do some postprocessing to get this information. 

In your case, I think the allocation is probably [powerwall, grid, solar] based on the following reasoning:

- Your rules say you shouldn't be discharging the powerwall into the grid. So if the powerwall is used in a period, as much power as possible should be allocated to meeting household demand. (By definition, any excess must be exported - but from what you say, this should not happen often).
- Solar is your lowest priority on the basis that you can export excess solar, but not pw or grid power. And with the way pwdusage works, it takes total available supply and then applies it to first meet home demand and then checks if there is any excess grid supply that should be applied to pw charging. It ignores all other excess on the basis that this is allocated between charging (measured and don't care), export (measured by Tesla and the utility), and losses (not measured).

With this this setup, you get:

- If the pw discharges, it is allocated to the house. 
- If the pw supply is not enough, the house then takes from the grid. Excess grid supply is then allocated to pw charging. 
- If these two supplies aren't enough, the house then takes from solar. Excess solar is assumed to go to export and charging.

Export is whatever the tesla reported, and pwdusage doesn't try to work out where it came from. 

You could also make a case for changing the order to [powerwall, solar, grid], but I think you are better with the first option as it maximises unallocated solar for use in charging or exporting (again, in accounting terms only - pwdusage works with historical data, not system operation). 

I do note that I can get away with playing a bit fast and loose with the rules because:
- It's a closed system with all supplies and grid export well measured.
- The energy balance mostly just works (and when it doesn't, tesla magic that I'm not going to try and reverse engineer applies).
- The supply priority is an internal accounting trick to get a rough valuation of the solar and the battery - the actual utility metering doesn't see this at all. But I've done some cross checks looking at what power costs would be with and without the system and the logic I've implemented matches this.

> The same concerns would be on the Report section. 

As the documentation says, you can pick and choose what you report, and then manipulate it further in grafana. Pretty well everything in this [string table](https://github.com/BuongiornoTexas/pwdusage#strings-from-commonpy) can be reported - and if I understand your utility plan correctly, this should provide all of the building blocks you might need to create variations on the way I've done the calculations, or put something entirely new together. 

(My attitude is I've done one possible implementation - almost certainly not the best one - so, I'm happy to see what others come up!)

**Comment by aesculus** [comment]
Great info. Over the next few days I will take a stab at setting it up and report my findings.

**Comment by aesculus** [comment]
All working properly now.
